# Generated by Django 5.1 on 2025-01-10 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repont', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('ip', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=1)),
                ('repont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repont.repont')),
            ],
        ),
    ]
