# Generated by Django 5.1 on 2025-01-11 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repont', '0002_statement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repont',
            name='state',
        ),
        migrations.AlterField(
            model_name='statement',
            name='repont',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_statments', to='repont.repont'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='state',
            field=models.CharField(choices=[('1', 'Működik'), ('2', 'Hibás'), ('3', 'Nincs adat')], max_length=1),
        ),
    ]
