# Generated by Django 5.1 on 2025-01-11 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repont', '0003_remove_repont_state_alter_statement_repont_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='repont',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_statements', to='repont.repont'),
        ),
    ]
