# Generated by Django 5.1 on 2025-01-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repont', '0004_alter_statement_repont'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repont',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
