# Generated by Django 5.1 on 2025-01-12 17:33

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repont', '0005_statement_description_alter_repont_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='repont',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repont',
            name='created_ip',
            field=models.CharField(default=datetime.datetime(2025, 1, 12, 17, 33, 46, 561250, tzinfo=datetime.timezone.utc), max_length=15),
            preserve_default=False,
        ),
    ]
